### ISSUE TITLE
Make the project run by using "cargo run"

### ISSUE THREAD

**Issue by AudranTourneur** [c2i-junia/minecraft-rust#106]
The project currently uses a bunch of ad-hoc scripts to build and run the project in debug mode, this is clearly bad practice and a better solution should be found.

Problems arise because of the following things:
- The executable needs to references external files, specifically game assets and save files.
- Dynamic linking is used in development mode, which requires us to specify the path to the Rust stdlib and Bevy dynamic libs.

A better solution would be to do the following thing:
- Run the project using `cargo run --bin client --features=bevy/dynamic_linking` (which seems to already kind of work!)
- Add a flag to specify the game folder at runtime, e.g. `--game-dir`, if the flag is not set, the current directory could be used. In the future it might be best to follow the [XDG specification](https://wiki.archlinux.org/title/XDG_Base_Directory).

**Comment by eztaah** [comment]
Before attempting to resolve this issue, careful consideration is required. The idea is to distribute the game as a folder that contains the executable along with the saves, assets, and other required files. 

This approach is similar to what Factorio does, and it proves to be much more practical for managing multiple versions of the game on the same machine. 

Therefore, it’s important to retain the concept of "game folder creation" as part of the build process.
