### ISSUE TITLE
Add hotbar

### ISSUE THREAD

**Issue by eztaah** [c2i-junia/minecraft-rust#27]
Pour simplifier, on peut dire que l'inventaire complet est dans cette hotbar. 

On a donc 9 cases d'inventaire, et on peut stocker jusqu'à 64 blocs par case

**Comment by mizkyosia** [comment]
Base Inventory dialog done, with possibilities to easily expand it

TODO : Hotbar for easy access to 1st row of inventory, block placing based on selected block in hotbar

**Comment by mizkyosia** [comment]
Hotbar done, now with mouse scrolling
